
INSERT INTO contactoffice (firma, kontakt, telefon, fax, email, strasse, hausnr, hausnrzus, plz, ort) VALUES
('Elektrosmog GmbH', 'Herr Alien', '+49.30.5555.1512', '+49.30.5555.1514', 'alien@elektrosmog.com',
	'Maxstrasse', '23', 'A', '13353', 'Berlin'),
('Kurzschluß GmbH', 'Frau Fertig', '+49.30.5555.4455', '+49.30.2343.4455', 'fertig@kurzschluss.de',
	'Schillerstraße', '99', 'B', '13353', 'Berlin'),
('Kabelsalat GmbH', 'Herr Glibber', '+49.30.5555.3345', '+49.30.2343.2121', 'glibber@kabelsalat.de',
	'Ruhestraße', '14', '', '13373', 'Berlin');

INSERT INTO signalquelle (tlevel, sq_idx, co_idx, sq_type, strasse, hausnr, hausnrzus, plz, ort, land, region) VALUES
(-1, 0, 2, 2, 'Reinickendorfer Strasse', '94', '', '13353', 'Berlin', 1, 1),
(-1, 0, 3, 3, 'Müller Strasse', '87', 'E', '13350', 'Berlin', 1, 1),
(-1, 0, 2, 1, 'Reinickendorfer Strasse', '45', '', '13353', 'Berlin', 1, 1),
(-1, 3, 2, 2, 'Afrikanische Straße', '56', 'G', '13347', 'Berlin', 1, 1),
(-1, 4, 2, 3, 'Reinickendorfer Strasse', '94', '', '13353', 'Berlin', 1, 1),
(-1, 4, 3, 2, 'Prinz-Eugen-Strasse', '13', '', '13354', 'Berlin', 1, 1),
(-1, 3, 2, 2, 'Afrikanische Straße', '56', 'G', '13347', 'Berlin', 1, 1),
(-1, 7, 2, 1, 'Reinickendorfer Strasse', '94', '', '13353', 'Berlin', 1, 1),
(-1, 7, 2, 3, 'Afrikanische Straße', '23', 'F', '13347', 'Berlin', 1, 1),
(-1, 7, 3, 1, 'Hansa Platz', '12', 'A', '11045', 'Berlin', 1, 1),
(-1, 10, 3, 4, 'Reinickendorfer Strasse', '90', '', '13353', 'Berlin', 1, 1),
(-1, 3, 2, 1, 'Hansa Platz', '123', 'A', '11045', 'Berlin', 1, 1),
(-1, 12, 3, 2, 'Reinickendorfer Strasse', '56', '', '13353', 'Berlin', 1, 1),
(-1, 0, 2, 1, 'Reinickendorfer Strasse', '56', '', '13353', 'Berlin', 1, 1),
(-1, 0, 2, 1, 'Sonnen Allee', '77', '', '12059', 'Berlin', 1, 1),
(-1, 15, 2, 1, 'Hansa Platz', '121', 'A', '11045', 'Berlin', 1, 1),
(-1, 0, 2, 2, 'Müller Strasse', '87', 'A', '13350', 'Berlin', 1, 1),
(-1, 0, 2, 1, 'Prinz-Eugen-Strasse', '23', '', '13354', 'Berlin', 1, 1),
(-1, 0, 2, 2, 'Reinickendorfer Strasse', '78', '', '13353', 'Berlin', 1, 1),
(-1, 19, 2, 2, 'Reinickendorfer Strasse', '88', '', '13353', 'Berlin', 1, 1),
(-1, 20, 2, 4, 'Prinz-Eugen-Strasse', '45', '', '13354', 'Berlin', 1, 1),
(-1, 21, 2, 4, 'Reinickendorfer Strasse', '87', '', '13353', 'Berlin', 1, 1),
(-1, 0, 2, 2, 'Reinickendorfer Strasse', '78', '', '13353', 'Berlin', 1, 1),
(-1, 0, 2, 1, 'Sonnen Allee', '79', '', '12059', 'Berlin', 1, 1);

-- TV Programm
INSERT INTO programm (pg_type, name, genre, land, sprache, www) VALUES
(1, '3sat', 'Kultur', 'Deutschland', 'deutsch', 'www.3sat.de'),
(1, '9Live', 'Unterhaltung', 'Deutschland', 'deutsch', 'http://www.neunlive.de/'),
(1, 'ARD', 'Unterhaltung', 'Deutschland', 'deutsch', 'http://www.daserste.de'),
(1, 'ARTE', 'Kultur', 'Deutschland', 'deutsch', 'http://www.arte-tv.com'),
(1, 'Astro TV', '', 'Deutschland', 'deutsch', 'http://www.questico.com/users/astrotv/'),
(1, 'ATV', '', 'Türkei', 'türkisch', 'http://www.atv.com.tr'),
(1, 'Alice', '', 'Italien', 'italienisch', 'http://www.alice.tv'),
(1, 'ATV Avrupa', '', 'Türkei', 'türkisch', 'http://www.atv.com.tr'),
(1, 'Bahn TV', '', 'Deutschland', 'deutsch', 'http://www.bahntv-online.de'),
(1, 'Bayerisches Fernsehen', 'Unterhaltung', 'Deutschland', 'deutsch', 'http://www.br-online.de'),
(1, 'BBC', '', 'Großbritannien', 'englisch', 'http://www.bbc.co.uk'),
(1, 'Beate-Uhse.TV', 'Erotik', 'Deutschland', 'deutsch', 'http://www.beate-uhse.tv'),
(1, 'Bibel TV', '', 'Deutschland', 'deutsch', 'http://www.bibeltv.de'),
(1, 'Bloomberg TV', 'Business', '-', 'deutsch', 'http://www.bloomberg.com/tv/'),
(1, 'BR-alpha', 'Bildung', 'Deutschland', 'deutsch', 'http://www.br-alpha.de'),
(1, 'Bundespresseamt', 'Nachrichten', 'Deutschland', 'deutsch', 'http://www.bundespresseamt.de'),
(1, 'Canal 24 Horas', '', 'Spanien', 'spanisch', 'http://www.rtve.es/tve/informa/24horas/'),
(1, 'CCTV 4', '', 'China', 'chinesisch', 'http://www.cctv-4.com'),
(1, 'CCTV 9', '', 'China', 'englisch', 'http://www.cctv-9.com'),
(1, 'CNN Deutschland', 'Nachrichten', 'Deutschland', 'deutsch', 'http://europe.cnn.com/CNNI/'),
(1, 'Count Down TV Italy', '', 'Italien', 'italienisch', 'http://www.rtdgroup.it'),
(1, 'Discovery Channel Germany', '', 'Deutschland', 'deutsch', 'http://www.discovery.de'),
(1, 'Disney Channel DE', 'Kinder', 'Deutschland', 'deutsch', 'http://www.disney.de/disneychannel/'),
(1, 'DMAX', 'Unterhaltung', 'Deutschland', 'deutsch', 'http://www.dmaxtv.de'),
(1, 'DSF', 'Sport', 'Deutschland', 'deutsch', 'http://www.dsf.de'),
(1, 'Deutsche Welle TV', 'Nachrichten', 'Deutschland', 'deutsch', 'http://www.dw-world.de'),
(1, 'Dubai EDTV', '', 'Arabische Länder', 'arabisch', 'http://www.dubaitv.ae/'),
(1, 'Eins Plus', 'Unterhaltung', 'Deutschland', 'deutsch', 'www.ard-digital.de/home/index.ph27'),
(1, 'Erotic First', 'Erotik', 'Deutschland', 'deutsch', 'http://www.erotikfirst.com/'),
(1, 'ERT SAT', '', 'Griechenland', 'griechisch', 'http://tvradio.ert.gr/en/world.asp'),
(1, 'Eurosport', 'Sport', 'Deutschland', 'deutsch', 'http://www.eurosport.de'),
(1, 'Eurosport News', 'Nachrichten', 'Frankreich', 'spanisch', 'http://www.euronews.net'),
(1, 'France 2', '', 'Frankreich', 'französich', '	http://www.france2.fr'),
(1, 'France 3', '', 'Frankreich', 'französich', 'http://www.france3.fr'),
(1, 'Franken SAT', '', 'Deutschland', 'deutsch', 'http://www.tvtouring.de'),
(1, 'Free-X TV', '', 'Niederlande', 'Niederl?ndisch', 'http://www.free-xtv.com'),
(1, 'GigaTV', 'Unterhaltung', 'Deutschland', 'deutsch', 'www.giga.tv'),
(1, 'GOD Channel', 'Religion', 'Großbritannien', 'englisch', 'http://www.god.tv'),
(1, 'Goldstar TV', '', 'Deutschland', 'deutsch', 'http://www.goldstar-tv.de/'),
(1, 'Heimatkanal', '', 'Deutschland', 'deutsch', 'http://www.heimatkanal.de'),
(1, 'HSE Home Shopping Europe', 'Shopping', 'Deutschland', 'deutsch', 'http://www.hse24.de'),
(1, 'HRT 1', '', 'Kroatien', 'kroatisch', 'http://www.hrt.hr'),
(1, 'HRT 2', '', 'Kroatien', 'kroatisch', 'http://www.hrt.hr'),
(1, 'HRT-SAT', '', 'Kroatien', 'kroatisch', 'http://www.hrt.hr/hrtsat/'),
(1, 'Junior Premiere', 'Kinder', 'Deutschland', 'deutsch', 'http://www.premiere.de/'),
(1, 'Kabel 1', 'Unterhaltung', 'Deutschland', 'deutsch', 'http://www.kabel1.de'),
(1, 'Kanal 105', 'Vollerotik', 'Deutschland', 'deutsch', 'http://www.kabelvision.de/hotx.php'),
(1, 'KI.KA', 'Kinder', 'Deutschland', 'deutsch', 'http://www.kika.de/'),
(1, 'Kinowelt TV', '', 'Deutschland', 'deutsch', 'http://www.kinowelt.tv'),
(1, 'Leonardo', '', 'Italien', 'italienisch', 'http://www.leonardo.tv/'),
(1, 'Lig TV', '', 'Türkei', 'türkisch', 'http://www.ligtv.com.tr/'),
(1, 'Magyar Televizio 1', '', 'Ungarn', 'ungarisch', 'http://www.mtv.hu'),
(1, 'Magyar Televizio 2', '', 'Ungarn', 'ungarisch', 'http://www.mtv.hu/'),
(1, 'MDR Fernsehen', 'Unterhaltung', 'Deutschland', 'deutsch', 'http://www.mdr.de/tv/'),
(1, 'MGM Premiere', '', 'Deutschland', 'deutsch', 'http://www.mgmchannel.de'),
(1, 'Motors TV', '', 'Frankreich', 'deutsch', 'http://www.motorstv.com/'),
(1, 'MTV 2 Pop', 'Musik', 'Deutschland', 'deutsch', 'http://www.mtvpop.de/'),
(1, 'MTV Base', 'Musik', 'Großbritannien', 'englisch', 'http://www.mtvbase.co.uk/'),
(1, 'MTV Central Europe', 'Musik', 'Deutschland', 'deutsch', 'http://www.mtv.tv/'),
(1, 'N24', 'Nachrichten', 'Deutschland', 'deutsch', 'http://www.n24.de'),
(1, 'Nashe Kino RTVi', '', 'Großbritannien', 'russisch', 'http://www.rtvi.ru'),
(1, 'NBC Europe', 'Nachrichten', 'Deutschland', 'englisch', 'http://www.giga.de/'),
(1, 'NDR-Fernsehen', 'Unterhaltung', 'Deutschland', 'deutsch', 'http://www.ndrtv.de'),
(1, 'n-tv', 'Nachrichten', 'Deutschland', 'deutsch', 'http://www.n-tv.de'),
(1, 'NTV Mir', '', 'Russland', 'russisch', 'http://www.ntvmir.com/'),
(1, 'Nuvolari', '', 'Italien', 'italienisch', 'http://www.nuvolari.tv/'),
(1, 'ORF1', 'Unterhaltung', 'Österreich', 'deutsch', 'http://www.orf.at'),
(1, 'ORF2', 'Unterhaltung', 'Österreich', 'deutsch', 'http://www.orf.at'),
(1, 'ORT international', '', 'Russland', 'russisch', 'http://www.1tv.ru/'),
(1, 'Phoenix', 'Nachrichten', 'Deutschland', 'deutsch', 'http://www.phoenix.de'),
(1, 'Planet (Premiere)', '', 'Deutschland', 'deutsch', 'http://www.planet-tv.de'),
(1, 'Premiere 1', '', 'Deutschland', 'deutsch', 'http://www.premiere.de'),
(1, 'Premiere 2', '', 'Deutschland', 'deutsch', 'http://www.premiere.de'),
(1, 'Premiere 3', '', 'Deutschland', 'deutsch', 'http://www.premiere.de'),
(1, 'Premiere 4', '', 'Deutschland', 'deutsch', 'http://www.premiere.de'),
(1, 'Premiere 5', '', 'Deutschland', 'deutsch', 'http://www.premiere.de'),
(1, 'Premiere 6', '', 'Deutschland', 'deutsch', 'http://www.premiere.de'),
(1, 'Premiere 7', '', 'Deutschland', 'deutsch', 'http://www.premiere.de'),
(1, 'Premiere Direkt (Portal)', '', 'Deutschland', 'deutsch', 'http://www.premiere.de'),
(1, 'Premiere Erotik (Erotik 1)', '', 'Deutschland', 'deutsch', 'http://www.premiere.de'),
(1, 'Premiere Krimi', '', 'Deutschland', 'deutsch', 'http://www.premiere.de'),
(1, 'Premiere Nostalgie', '', 'Deutschland', 'deutsch', 'http://www.premiere.de'),
(1, 'Premiere Serie', '', 'Deutschland', 'deutsch', 'http://www.premiere.de'),
(1, 'Premiere Sport 1', '', 'Deutschland', 'deutsch', 'http://www.premiere.de'),
(1, 'Premiere Sport 2', '', 'Deutschland', 'deutsch', 'http://www.premiere.de'),
(1, 'Premiere Start', '', 'Deutschland', 'deutsch', 'http://www.premiere.de'),
(1, 'Pro 7', 'Unterhaltung', 'Deutschland', 'deutsch', 'http://www.prosieben.de'),
(1, 'Pro TV International', '', 'Rumänien', 'rumänisch', 'http://www.protvintl.ro'),
(1, 'QVC Deutschland', 'Shopping', 'Deutschland', 'deutsch', 'http://www.qvc.de'),
(1, 'RAI UNO', '', 'Italien', 'italienisch', 'http://www.raiuno.rai.it/'),
(1, 'RAI DUE', '', 'Italien', 'italienisch', 'http://www.raidue.rai.it/'),
(1, 'RAI TRE', '', 'Italien', 'italienisch', 'http://www.raitre.rai.it/'),
(1, 'Raze TV', '', 'Deutschland', 'deutsch', 'http://www.raze.tv/'),
(1, 'RBB Berlin', '', 'Deutschland', 'deutsch', 'http://www.rbb-online.de/fernsehen/'),
(1, 'RBB Brandenburg', '', 'Deutschland', 'deutsch', 'http://www.rbb-online.de/fernsehen/'),
(1, 'Rhein-Main TV', '', 'Deutschland', 'deutsch', 'http://www.rheinmaintv.de'),
(1, 'RTL', 'Unterhaltung', 'Deutschland', 'deutsch', 'http://www.rtl-television.de'),
(1, 'RTL 2', 'Unterhaltung', 'Deutschland', 'deutsch', 'http://www.rtl2.de'),
(1, 'RTL Shop', '', 'Deutschland', 'deutsch', 'http://www.rtlshop.de'),
(1, 'RTP Internacional', '', 'Portugal', 'portugiesisch', 'http://programas.rtp.pt/EPG/tv/'),
(1, 'RTR Planeta', '', 'Russland', 'russisch', 'http://www.rtr-planeta.com'),
(1, 'RTVi', '', 'Russland', 'russisch', 'http://www.rtvi.ru/'),
(1, 'Sat 1', 'Unterhaltung', 'Deutschland', 'deutsch', 'http://www.sat1.de'),
(1, 'SciFi Deutschland', '', 'Deutschland', 'deutsch', 'http://www.scifi.de'),
(1, 'National Geographic', 'Dokumenatär', 'Italien', 'deutsch', 'http://deutschland.ngceurope.com'),
(1, 'Show TV', '', 'Türkei', 'türkisch', 'http://www.showtvnet.com'),
(1, 'Sinema Turk', '', 'Türkei', 'türkisch', 'http://www.digiturk.tv/channel/?channel='),
(1, 'Silverline Movie Channel', '', 'Deutschland', 'deutsch', 'http://www.silverlinetv.de'),
(1, 'Sonnenklar TV', '', 'Deutschland', 'deutsch', 'http://www.sonnenklar.tv/'),
(1, 'Spi.Ka TV', '', 'Deutschland', 'deutsch', 'http://www.spika.tv/'),
(1, 'SR Südwest Fernsehen', 'Unterhaltung', 'Deutschland', 'deutsch', 'http://www.sr-online.de'),
(1, 'Super RTL', 'Kinder', 'Deutschland', 'deutsch', 'http://www.superrtl.de'),
(1, 'SWR Baden-Württemberg', '', 'Deutschland', 'deutsch', 'http://www.swr.de/tv/'),
(1, 'SWR Rheinland-Pfalz', 'Unterhaltung', 'Deutschland', 'deutsch', 'http://www.swr.de/tv/'),
(1, 'Tele 5', '', 'Deutschland', 'deutsch', 'http://www.tele5.de/'),
(1, 'TF1', '', 'Frankreich', 'französich', 'http://www.tf1.fr'),
(1, 'TGRT Europe', '', 'Deutschland', 'türkisch', 'http://www.tgrteu.de'),
(1, 'TRT International', '', 'Türkei', 'türkisch', 'http://www.tgrteu.de'),
(1, 'TV Polonia', '', 'Polen', 'polnisch', 'http://www.tv7.bg'),
(1, 'TV Travel Shop Germany', '', 'Deutschland', 'deutsch', 'http://www.tvtravelshop.de'),
(1, 'tv.berlin', '', 'Deutschland', 'deutsch', 'http://www.tvb.de'),
(1, 'TV5 Europe', '', 'Frankreich', 'französich', 'http://www.tv5.org/'),
(1, 'TVE Internacional', '', 'Spanien', 'spanisch', 'http://www.rtve.es/canales/tveinter/'),
(1, 'TVN', '', 'Polen', 'polnisch', 'http://www.tvn.pl'),
(1, 'TW1', 'Wetter', 'Österreich', 'deutsch', 'http://www.tw1.at'),
(1, 'Viva', 'Musik', 'Deutschland', 'deutsch', 'http://www.viva.tv'),
(1, 'Viva Plus', 'Musik', 'Deutschland', 'deutsch', 'http://www.vivaplus.tv'),
(1, 'VOX', 'Unterhaltung', 'Deutschland', 'deutsch', 'http://www.vox.de'),
(1, 'VTV 4', '', 'Vietnam', 'vietnamesisch', 'http://www.vtv.org.vn'),
(1, 'WDR', '', 'Deutschland', 'deutsch', 'http://www.wdr.de/tv/'),
(1, 'WDR Fernsehen Köln', '', 'Deutschland', 'deutsch', 'http://www.wdr.de/tv/'),
(1, 'WDR Studio Aachen', '', 'Deutschland', 'deutsch', 'http://www.wdr.de/studio/aachen/'),
(1, 'WDR Studio Bielefeld', '', 'Deutschland', 'deutsch', 'http://www.wdr.de/studio/bielefeld/'),
(1, 'WDR Studio Dortmund', '', 'Deutschland', 'deutsch', 'http://www.wdr.de/studio/dortmund/'),
(1, 'WDR Studio Düsseldorf', '', 'Deutschland', 'deutsch', 'http://www.wdr.de/studio/duesseldorf/'),
(1, 'WDR Studio Essen', '', 'Deutschland', 'deutsch', 'http://www.wdr.de/studio/essen/'),
(1, 'WDR Studio Münster', '', 'Deutschland', 'deutsch', 'http://www.wdr.de/studio/muenster/'),
(1, 'WDR Studio Siegen', '', 'Deutschland', 'deutsch', 'http://www.wdr.de/studio/siegen/'),
(1, 'WDR Studio Wuppertal', '', 'Deutschland', 'deutsch', 'http://www.wdr.de/studio/wuppertal/'),
(1, 'Wellenlänge TV', '', 'Deutschland', 'deutsch', 'http://www.wellenlaenge.tv'),
(1, 'ZDF', 'Unterhaltung', 'Deutschland', 'deutsch', 'http://www.zdf.de'),
(1, 'ZDF Dokukanal', 'Dokumentär', 'Deutschland', 'deutsch', 'http://www.zdfdokukanal.de'),
(1, 'ZDF Infokanal', 'Nachrichten', 'Deutschland', 'deutsch', 'http://www.zdfinfokanal.de'),
(1, 'ZDF Theaterkanal', 'Kultur', 'Deutschland', 'deutsch', 'http://www.theaterkanal.de');

-- Radio Programm
INSERT INTO programm (pg_type, name, land, sprache) VALUES
(2, '104.6 RTL', 'Deutschland', 'deutsch'),
(2, '89.0 RTL', 'Deutschland', 'deutsch'),
(2, 'AFN Z-FM', 'Deutschland', 'deutsch'),
(2, 'Antenne Thueringen', 'Deutschland', 'deutsch'),
(2, 'Antenne Brandenburg', 'Deutschland', 'deutsch'),
(2, 'Bayern 1', 'Deutschland', 'deutsch'),
(2, 'Bayern 3', 'Deutschland', 'deutsch'),
(2, 'BB Radio', 'Deutschland', 'deutsch'),
(2, 'BFBS Radio 1 Germany', 'Deutschland', 'deutsch'),
(2, 'Chart Radio', 'Deutschland', 'deutsch'),
(2, 'DeutschlandRadio Berlin', 'Deutschland', 'deutsch'),
(2, 'DomRadio', 'Deutschland', 'deutsch'),
(2, 'DW Deutsche Welle', 'Deutschland', 'deutsch'),
(2, 'Energy Berlin', 'Deutschland', 'deutsch'),
(2, 'ERF Radio', 'Deutschland', 'deutsch'),
(2, 'Fritz', 'Deutschland', 'deutsch'),
(2, 'Hellas Live', 'Deutschland', 'deutsch'),
(2, 'Hit Radio FFH', 'Deutschland', 'deutsch'),
(2, 'HitRadio Antenne Niedersachsen', 'Deutschland', 'deutsch'),
(2, 'HR Info', 'Deutschland', 'deutsch'),
(2, 'HR1 Hessischer Rundfunk', 'Deutschland', 'deutsch'),
(2, 'HR3 Hessischer Rundfunk', 'Deutschland', 'deutsch'),
(2, 'Hundert,6', 'Frankreich', 'französisch'),
(2, 'JAM FM', 'Deutschland', 'deutsch'),
(2, 'Kiss FM 98.8 FM', 'Deutschland', 'deutsch'),
(2, 'Kiss Radio München', 'Deutschland', 'deutsch'),
(2, 'Landeswelle Thueringen', 'Deutschland', 'deutsch'),
(2, 'MDR Info', 'Deutschland', 'deutsch'),
(2, 'MDR Klassik', 'Deutschland', 'deutsch'),
(2, 'NDR 2', 'Deutschland', 'deutsch'),
(2, 'NDR Kultur', 'Deutschland', 'deutsch'),
(2, 'NordwestRadio (Radio Bremen)', 'Deutschland', 'deutsch'),
(2, 'Oldie 95', 'Deutschland', 'deutsch'),
(2, 'P.O.S. Radio', 'Deutschland', 'deutsch'),
(2, 'R.SA', 'Deutschland', 'deutsch'),
(2, 'Radio Bremen 4', 'Deutschland', 'deutsch'),
(2, 'Radio Eins', 'Deutschland', 'deutsch'),
(2, 'Radio Horeb', 'Deutschland', 'deutsch'),
(2, 'Radio Neue Hoffnung', 'Deutschland', 'deutsch'),
(2, 'Radio Paradiso 98.2 FM', 'Deutschland', 'deutsch'),
(2, 'Radio Regenbogen', 'Deutschland', 'deutsch'),
(2, 'Radio SAW', 'Deutschland', 'deutsch'),
(2, 'Radio Venera', 'Deutschland', 'deutsch'),
(2, 'RBB RADIOmultikulti 106.8 FM', 'Deutschland', 'deutsch'),
(2, 'Rockland Sachsen-Anhalt', 'Deutschland', 'deutsch'),
(2, 'RS2 94.3 FM', 'Deutschland', 'deutsch'),
(2, 'Spreeradio 105.5 FM', 'Deutschland', 'deutsch'),
(2, 'SR1 Europawelle', 'Deutschland', 'deutsch'),
(2, 'SR3 Saarlandwelle', 'Deutschland', 'deutsch'),
(2, 'Sunshine Live', 'Deutschland', 'deutsch'),
(2, 'SWR 1 Rheinland-Pfalz', 'Deutschland', 'deutsch'),
(2, 'SWR 3', 'Deutschland', 'deutsch'),
(2, 'SWR 4 Rheinland-Pfalz', 'Deutschland', 'deutsch'),
(2, 'WDR Eins Live', 'Deutschland', 'deutsch'),
(2, 'WDR VERA (Verkehrskanal)', 'Deutschland', 'deutsch'),
(2, 'WDR2 Klassik', 'Deutschland', 'deutsch'),
(2, 'WDR4', 'Deutschland', 'deutsch'),
(2, 'You FM - Young Fresh Music', 'Deutschland', 'deutsch'),
(2, '88 Acht', 'Deutschland', 'deutsch'),
(2, 'AFN Power Network', 'Deutschland', 'deutsch'),
(2, 'Antene Mecklenburg-Vorpommern', 'Deutschland', 'deutsch'),
(2, 'Antenne Bayern', 'Deutschland', 'deutsch'),
(2, 'B5 Aktuell', 'Deutschland', 'deutsch'),
(2, 'Bayern 2 Radio', 'Deutschland', 'deutsch'),
(2, 'Bayern 4 Klassik', 'Deutschland', 'deutsch'),
(2, 'Berliner Rundfunk 91.4 FM', 'Deutschland', 'deutsch'),
(2, 'Big FM', 'Deutschland', 'deutsch'),
(2, 'Das Ding', 'Deutschland', 'deutsch'),
(2, 'DLF Deutschlandfunk', 'Deutschland', 'deutsch'),
(2, 'DW Deutsche Welle (Foreign)', 'Deutschland', 'deutsch'),
(2, 'DW Radio M', 'Deutschland', 'deutsch'),
(2, 'Energy München', 'Deutschland', 'deutsch'),
(2, 'EuroSpar Music', 'Deutschland', 'deutsch'),
(2, 'Harmony FM', 'Deutschland', 'deutsch'),
(2, 'Hit Mix FM', 'Deutschland', 'deutsch'),
(2, 'Hit-Radio Antenne 1', 'Deutschland', 'deutsch'),
(2, 'HitRadio RTL', 'Deutschland', 'deutsch'),
(2, 'HR Klassik', 'Deutschland', 'deutsch'),
(2, 'HR2 Hessischer Rundfunk', 'Deutschland', 'deutsch'),
(2, 'HR4 Hessischer Rundfunk', 'Deutschland', 'deutsch'),
(2, 'InfoRadio', 'Deutschland', 'deutsch'),
(2, 'Jazz Radio', 'Deutschland', 'deutsch'),
(2, 'Kiss Radio + München', 'Deutschland', 'deutsch'),
(2, 'Klassik Radio', 'Deutschland', 'deutsch'),
(2, 'MDR Figaro', 'Deutschland', 'deutsch'),
(2, 'MDR Jump', 'Deutschland', 'deutsch'),
(2, 'Metropol FM 94.8', 'Deutschland', 'deutsch'),
(2, 'NDR Info', 'Deutschland', 'deutsch'),
(2, 'N-Joy', 'Deutschland', 'deutsch'),
(2, 'Nova Radio', 'Deutschland', 'deutsch'),
(2, 'Orion Network (IC Radio)', 'Deutschland', 'deutsch'),
(2, 'Planet Radio', 'Deutschland', 'deutsch'),
(2, 'Radio Biser', 'Deutschland', 'deutsch'),
(2, 'Radio Bremen Eins', 'Deutschland', 'deutsch'),
(2, 'Radio Hamburg', 'Deutschland', 'deutsch'),
(2, 'Radio Melodie', 'Deutschland', 'deutsch'),
(2, 'Radio NRW', 'Deutschland', 'deutsch'),
(2, 'Radio PSR', 'Deutschland', 'deutsch'),
(2, 'Radio Salü', 'Deutschland', 'deutsch'),
(2, 'Radio Top 40', 'Deutschland', 'deutsch'),
(2, 'RBB Kulturradio', 'Deutschland', 'deutsch'),
(2, 'Rock Antenne', 'Deutschland', 'deutsch'),
(2, 'RPR Eins', 'Deutschland', 'deutsch'),
(2, 'Sky Radio Hessen', 'Deutschland', 'deutsch'),
(2, 'Sputnik', 'Deutschland', 'deutsch'),
(2, 'SR2 Kultur', 'Deutschland', 'deutsch'),
(2, 'Star FM - Der Rocksender 87.9', 'Deutschland', 'deutsch'),
(2, 'SWR 1 Baden Württemberg', 'Deutschland', 'deutsch'),
(2, 'SWR 2', 'Deutschland', 'deutsch'),
(2, 'SWR 4 Baden Württemberg', 'Deutschland', 'deutsch'),
(2, 'SWR Cont.Ra', 'Deutschland', 'deutsch'),
(2, 'WDR Funkhaus Europa', 'Deutschland', 'deutsch'),
(2, 'WDR2', 'Deutschland', 'deutsch'),
(2, 'WDR3', 'Deutschland', 'deutsch'),
(2, 'WDR5', 'Deutschland', 'deutsch'),
(2, 'Deutschland Radio Kultur', 'Deutschland', 'deutsch'),
(2, '104.6 Boah FM', 'Deutschland', 'deutsch'),
(2, 'Oldie FM', 'Deutschland', 'deutsch'),
(2, 'BBC', 'Großbritannien', 'englisch'),
(2, 'RTL - Oldies', 'Deutschland', 'deutsch'),
(2, 'Motor FM', 'Deutschland', 'deutsch'),
(2, 'Radio TEDDY', 'Deutschland', 'deutsch'),
(2, 'Radio Multikulti', 'Deutschland', 'deutsch'),
(2, 'Worl Radio Network', '', ''),
(2, 'Radio Kultur', 'Deutschland', 'deutsch'),
(2, 'OKB (russ.)', 'Russland', 'russisch'),
(2, 'Radio France Inter.', 'Frankreich', 'französich'),
(2, 'Eins Live', 'Deutschland', 'deutsch'),
(2, 'Offener Kanal', 'Deutschland', 'deutsch'),
(2, 'WRN (englisch)', 'Großbritannien', 'englisch'),
(2, 'Ostseewelle', 'Deutschland', 'deutsch'),
(2, 'HR XXL', 'Deutschland', 'deutsch'),
(2, 'NDR1 (MV)', 'Deutschland', 'deutsch'),
(2, 'SWF1', 'Deutschland', 'deutsch'),
(2, 'SWF2', 'Deutschland', 'deutsch'),
(2, 'SWF3', 'Deutschland', 'deutsch'),
(2, 'SWF4', 'Deutschland', 'deutsch'),
(2, 'Radio MK', 'Deutschland', 'deutsch'),
(2, 'Radio EN', 'Deutschland', 'deutsch'),
(2, 'Radio Hagen', 'Deutschland', 'deutsch'),
(2, 'Radio Bochum', 'Deutschland', 'deutsch'),
(2, 'Radio Kiepenkerl', 'Deutschland', 'deutsch'),
(2, 'Radio Neandertal', 'Deutschland', 'deutsch'),
(2, 'Radio RTL', 'Deutschland', 'deutsch'),
(2, 'Radio 91,2', 'Deutschland', 'deutsch'),
(2, 'Radio Pink', 'Serbien', 'serbisch');

-- Bouquet
INSERT INTO programm (pg_type, name) VALUES
(3, 'DPC'),
(3, 'Premiere'),
(3, 'ZDF Vision'),
(3, 'ARD Digital 2'),
(3, 'ASTRA-HD'),
(3, 'DPC 2'),
(3, 'ARD Digital'),
(3, 'T-Systems'),
(3, 'RTL Group'),
(3, 'MTV Networks'),
(3, 'WDR'),
(3, 'VisAvision Basis'),
(3, 'VisAvision Türkisch'),
(3, 'VisAvision Italienisch'),
(3, 'VisAvision Russisch'),
(3, 'VisAvision Polnisch'),
(3, 'VisAvision Mix'),
(3, 'VisAvision Filmpaket'),
(3, 'VisAvision 1'),
(3, 'VisAvision 2'),
(3, 'IntTV 1'),
(3, 'IntTV 2'),
(3, 'IntTV 3'),
(3, 'IntTV 4');

INSERT INTO sbprovider (firma, land, www, iskabprov) VALUES
('SES, Societe Anonyme', 'Luxembourg', 'http://www.ses-astra.com', 0),
('Eutelsat Communications S.A.', 'France', 'http://www.eutelsat.com', 0),
('Türksat Bilgi Teknolojileri', 'Türkei', 'http://www.turksat.com.tr', 0),
('Unity Media GmbH', 'Deutschland', 'http://www.unitymedia.de/', 1),
('Kabel Baden-Württemberg GmbH & Co. KG', 'Deutschland', 'http://www.kabelbw.de/', 1),
('Tele Columbus GmbH', 'Deutschland', 'http://www.telecolumbus.de/', 1),
('Kabel Deutschland', 'Deutschland', 'http://www.kabeldeutschland.de', 1),
('Primacom', 'Deutschland', 'http://www.primacom.de/', 1),
('RBB', 'Brandenburg', '', 0),
('RBB', 'Berlin', '', 0),
('SWR', 'Baden-Württemberg', '', 0),
('BR', 'Bayern', '', 0),
('RB', 'Bremen', '', 0),
('HR', 'Hessen', '', 0),
('NDR', 'Hamburg', '', 0),
('NDR', 'Mecklenburg-Vorpommern', '', 0),
('NDR', 'Niedersachsen', '', 0),
('WDR', 'Nordrhein-Westfalen', '', 0),
('SWR', 'Rheinland-Pfalz', '', 0),
('NDR', 'Schleswig-Holstein', '', 0),
('SR', 'Saarland', '', 0),
('MDR', 'Sachsen', '', 0),
('MDR', 'Sachsen-Anhalt', '', 0),
('MDR', 'Thüringen', '', 0);

-- Satellit
INSERT INTO signalbezug (sb_type, kennung1, sat_pos, sat_codx) VALUES
(1, 'ASTRA 1F,1G,1H,1KR,1L', '19.2', '0192'),
(1, 'ASTRA 1D,3A', '23.5', '0235'),
(1, 'ASTRA 2A,B,C,D', '28.2', '0282'),
(1, 'EUROBIRD 1', '28.2', '0282'),
(1, 'EUTELSAT SESAT, W4', '36', '0360');

-- Kabel ÜP
INSERT INTO signalbezug (sb_type, kennung1, kennung2, up_strasse, up_hausnr, up_hausnrzus, up_plz, up_ort) VALUES
(2, '9515', '', 'Am Salzhaff', '9', '', '23966', 'Wismar'),
(2, '9517', '', 'Birkenweg', '5', '', '23970', 'Wismar'),
(2, '9520', '', 'Heinrich-Mann-Str.', '14', '', '23970', 'Wismar'),
(2, '9525', '', 'Professor-Frege-Str.', '42', '', '23970', 'Wismar'),
(2, '19922', '', 'Lübsche Str.', '188', '', '23968', 'Wismar'),
(2, '1783', '', 'Am Queckenberg', '1', '', '38120', 'Braunschweig'),
(2, '1793', '', 'Emsstr.', '10', '', '38120', 'Braunschweig'),
(2, '15086', '', 'Chamissostr.', '12', '', '31785', 'Hammeln'),
(2, '15094', '', 'Ellerbrook', '15', '', '31787', 'Hammeln'),
(2, '15303', '', 'Daimlerstr.', '6', '', '38446', 'Wolfsburg'),
(2, '20616', '', 'Beethovenring', '1', '', '38440', 'Wolfsburg'),
(2, '24443', 'REALBN', 'Gamigstr.', '20', '', '01239', 'Dresden'),
(2, '24442', 'REALBN', 'Gamigstr', '20', '', '01239', 'Dresden'),
(2, '24444', 'REALBN', 'Georg-Palitzsch-Str.', '5', '', '01239', 'Dresden'),
(2, '24618', 'REALBN', 'Alfred-Delp-Ring', '23', '', '99087', 'Erfurt'),
(2, '24963', 'REALBN', 'Alfred-Delp-Ring', '23', '', '99087', 'Erfurt');

-- Terrestrisch
INSERT INTO signalbezug (sb_type, kennung1, kennung2) VALUES
(3, 'Boossen', ''),
(3, 'Cottbus', ''),
(3, 'Berlin-Alexanderplatz', ''),
(3, 'Berlin-Schäferberg', ''),
(3, 'Berlin-Scholzplatz', ''),
(3, 'Baden-Baden', ''),
(3, 'Brandenkopf', ''),
(3, 'Donaueschingen', ''),
(3, 'Freiburg', ''),
(3, 'Heidelberg', ''),
(3, 'Hochrhein', '');

-- ----------------------------------------------------------------------------

UPDATE `signalbezug` SET `sbp_idx` = 1,`refcount` = 4 WHERE  `signalbezug`.`uidx` = 1;
UPDATE `signalbezug` SET `sbp_idx` = 1,`refcount` = 9 WHERE  `signalbezug`.`uidx` = 2;
UPDATE `signalbezug` SET `sbp_idx` = 1,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 3;
UPDATE `signalbezug` SET `sbp_idx` = 2,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 4;
UPDATE `signalbezug` SET `sbp_idx` = 2,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 5;
UPDATE `signalbezug` SET `sbp_idx` = 24,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 6;
UPDATE `signalbezug` SET `sbp_idx` = 23,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 7;
UPDATE `signalbezug` SET `sbp_idx` = 7,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 8;
UPDATE `signalbezug` SET `sbp_idx` = 6,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 9;
UPDATE `signalbezug` SET `sbp_idx` = 4,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 10;
UPDATE `signalbezug` SET `sbp_idx` = 24,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 11;
UPDATE `signalbezug` SET `sbp_idx` = 21,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 12;
UPDATE `signalbezug` SET `sbp_idx` = 22,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 13;
UPDATE `signalbezug` SET `sbp_idx` = 23,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 14;
UPDATE `signalbezug` SET `sbp_idx` = 24,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 15;
UPDATE `signalbezug` SET `sbp_idx` = 8,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 16;
UPDATE `signalbezug` SET `sbp_idx` = 9,`refcount` = 4 WHERE  `signalbezug`.`uidx` = 22;
UPDATE `signalbezug` SET `sbp_idx` = 9,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 23;
UPDATE `signalbezug` SET `sbp_idx` = 10,`refcount` = 2 WHERE  `signalbezug`.`uidx` = 24;
UPDATE `signalbezug` SET `sbp_idx` = 10,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 25;
UPDATE `signalbezug` SET `sbp_idx` = 10,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 26;
UPDATE `signalbezug` SET `sbp_idx` = 11,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 27;
UPDATE `signalbezug` SET `sbp_idx` = 11,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 28;
UPDATE `signalbezug` SET `sbp_idx` = 11,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 29;
UPDATE `signalbezug` SET `sbp_idx` = 11,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 30;
UPDATE `signalbezug` SET `sbp_idx` = 11,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 31;
UPDATE `signalbezug` SET `sbp_idx` = 11,`refcount` = 0 WHERE  `signalbezug`.`uidx` = 32;
UPDATE `signalbezug` SET `sbp_idx` = 3,`refcount` = 3 WHERE  `signalbezug`.`uidx` = 17;

-- ----------------------------------------------------------------------------

INSERT INTO `kabelprogfreq` (`uidx`, `pg_idx`, `sb_idx`, `sbp_idx`, `kf_idx`, `sig_type`, `bc_type`, `iscryp`) VALUES
(1, 2, 0, 5, 42, NULL, NULL, 0),
(2, 3, 0, 5, 43, NULL, NULL, 0),
(3, 4, 0, 5, 44, NULL, NULL, 0),
(4, 5, 0, 5, 45, NULL, NULL, 0),
(5, 6, 0, 5, 46, NULL, NULL, 0),
(6, 168, 0, 5, 150, NULL, NULL, 0),
(7, 169, 0, 5, 391, NULL, NULL, 0),
(8, 173, 0, 5, 0, NULL, NULL, 0),
(9, 174, 0, 5, 0, NULL, NULL, 0),
(10, 176, 0, 5, 0, NULL, NULL, 0),
(11, 302, 0, 5, 0, NULL, NULL, 0),
(12, 303, 0, 5, 0, NULL, NULL, 0),
(13, 304, 0, 5, 0, NULL, NULL, 0),
(14, 312, 0, 5, 0, NULL, NULL, 0),
(15, 294, 0, 5, 0, NULL, NULL, 0),
(16, 2, 0, 23, 0, NULL, NULL, 0),
(17, 3, 0, 23, 0, NULL, NULL, 0),
(18, 4, 0, 23, 0, NULL, NULL, 0),
(19, 5, 0, 24, 0, NULL, NULL, 0),
(20, 6, 0, 24, 0, NULL, NULL, 0),
(21, 7, 0, 24, 0, NULL, NULL, 0),
(22, 308, 0, 24, 0, NULL, NULL, 0);

INSERT INTO `satprogfreq` (`uidx`, `pg_idx`, `sb_idx`, `freq`, `zwfreq`, `polar`, `symbol`, `transp`, `spot`, `sig_type`, `bc_type`, `iscryp`) VALUES
(1, 3, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0),
(2, 5, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0),
(3, 6, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0),
(4, 9, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1),
(5, 5, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0),
(6, 6, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0),
(7, 55, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0),
(8, 273, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1),
(9, 274, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1),
(10, 276, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0),
(11, 303, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0),
(12, 304, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1),
(13, 311, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0),
(14, 11, 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0),
(15, 12, 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1),
(16, 13, 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);

INSERT INTO `terrprogfreq` (`uidx`, `pg_idx`, `sb_idx`, `freq`, `sig_type`, `bc_type`, `iscryp`) VALUES
(2, 6, 23, 23.2300, NULL, NULL, 0),
(3, 10, 23, 10.1500, NULL, NULL, 1),
(4, 11, 23, 11.2300, NULL, NULL, 1),
(5, 288, 23, 88.3450, NULL, NULL, 0),
(6, 295, 25, NULL, NULL, NULL, 0),
(7, 297, 25, NULL, NULL, NULL, 0);

